services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped

    ports:
      - "4000:8080"

    networks:
      - proxy

networks:
  proxy:
    external: true
